### ISSUE TITLE
Next stable version of Luma3DS will change path and break this

### ISSUE THREAD

**Issue by CouldBeWolf** [Possum/LumaLocaleSwitcher#9] opened 2016-11-25 08:47 UTC
[This commit](https://github.com/AuroraWright/Luma3DS/commit/b5336c81cc82b6c5e8115249342beb5b065cdce9) to Luma3DS changes paths and naming.

`"changed structure for game patches: language emulation txts now go to /luma/titles/<titleid>/locale.txt, code.bins go to /luma/titles/<titleid>/code.bin, RomFSes go to /luma/titles/<titleid>/romfs"`

**Comment by simonrule** [comment] 2016-11-26 14:30
yes i just got answer from **AuroraWright** and she said that lumalocalswitcher need to be updated
here what she did say
"The issue isn't in Luma, it's in that "locale switcher" app which needs to be updated for the new folder layout in nightlies (/luma/titles/titleID/locale.txt instead of /luma/locales/titleID.txt)."

**Comment by CouldBeWolf** [comment] 2016-12-02 23:29
If you bothered clicking the link it's already explained there, so no need to bother AuroaWright. I now see the formating broke my copy paste4, but I fixed it. But really, it was clearly explained.

**Comment by ericjwg** [comment] 2016-12-09 03:09
https://gbatemp.net/threads/lumalocaleswitcher-nightly-revision-need-help.452480/#post-6911043

**Comment by ericjwg** [comment] 2016-12-09 17:56
https://gbatemp.net/attachments/lumalocaleswitcher-rvn-7z.71667/ download this revision for nightly luma

**Comment by simonrule** [comment] 2016-12-09 20:05
thank you so much :)

**Comment by Possum** [comment] 2016-12-21 19:26
@ericjwg if you don't mind, can you get me a patch with the change(s) in your build? Or better yet, submit a pull request (so git history reflects the proper attribution).

**Comment by ericjwg** [comment] 2016-12-22 14:53
just saying... the revision remove all others setup. it only supports current luma nightly and future release luma

**Comment by gingerbeardman** [comment] 2017-03-06 15:35
This just caught me out: https://github.com/AuroraWright/Luma3DS/issues/350#issuecomment-284298999

Any chance of the fix being merged?

**Comment by Margen67** [comment] 2017-03-06 22:20
@Possum https://github.com/Possum/LumaLocaleSwitcher/pull/10

**Comment by Margen67** [comment] 2017-03-06 22:34
@gingerbeardman Most likely not. @Possum and this repo hasn't had any activity since 2016 so I presume this repository is dead.

**Comment by Possum** [comment] 2017-03-08 00:12
Astute observation.

Indeed, I've been quite ~~lazy~~ busy lately and haven't had time to come up with a way to implement this maintaining backwards compatibility (though at this point, that's probably not a necessary goal).

I pushed some code changes I've been sitting on that *might* do the trick. I haven't been able to get a build to run on my 3DS (likely toolchain issues on my end - everything I try to build is black screen), but it might build for others. Totally untested, so probably a good idea to keep a backup of your SD card if you run this just in case.

Once I figure out what's going on with my toolchain I'll try to upload a working build.

**Comment by Possum** [comment] 2017-03-10 03:26
Ok, more changes in master. It should compile and run now with the latest libctru.

There had been some substantial changes in the graphics libraries since I last touched the code so that's why I was getting weird results. I lifted the necessary changes from FBI's code base and now it runs. I also made some improvements and I think it's working acceptably with some basic testing. I'll release a CIA in the next couple of days.

Thanks for your patience :)

**Comment by ericjwg** [comment] 2017-03-10 03:28
cool!!!!

**Comment by ericjwg** [comment] 2017-03-10 03:32
https://puu.sh/uC5zW/5470adc347.7z

**Comment by Margen67** [comment] 2017-03-17 17:12
@Possum This needs to be addressed. People make invalid issues on the Luma3DS repo almost once a day because LumaLocaleSwitcher uses outdated paths meant for 6.6 Stable Luma3DS.
There's a working build here but most people will just get the latest release (0.02)

https://github.com/AuroraWright/Luma3DS/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20region

https://github.com/AuroraWright/Luma3DS/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20patching

**Comment by Possum** [comment] 2017-04-06 21:01
New builds are up.

I created two builds because I did not want to confuse users who are using the latest stable version of Luma3DS. It should *just work*™ for users running a stock setup. Users running *Luma NIGHTLY* have the option to change it, or download the "NIGHTLY" build for the defaults there.

FWIW I don't run Luma NIGHTLY on my primary system.

PS - I looked over those bugs in the Luma repository, and they did not seem to indicate any issues stemming from using this tool, and there were only a handful of reporters confused about the path change.

**Closed as completed by Possum** 2017-04-06 21:01 UTC
