### ISSUE TITLE
Issues with lasted nightly luma

### ISSUE THREAD

**Issue by Sonikato** [Possum/LumaLocaleSwitcher#13] opened 2017-04-12 03:37 UTC
Hi! im have a problem with luma local switcher, when i config the region and languaje this gone to discard inmediatly when i press b button.

im running 11.4 and luma nightly and the version of Luma Local Switcher es 0.03 nightly.

PS: Sorry for my bad english.

**Comment by McFork** [comment] 2017-04-14 13:53
Yeah there seems to be a real problem with locales.
But I don't think it comes from LumaLocaleSwitcher but from Luma3DS itself.
I tried modifying the languages manually directly on the SD card to the new location (/luma/titles/<titleid>/locale.txt) and it still doesn't work, event with game patching enabled.

**Comment by Possum** [comment] 2017-04-14 13:56
This may be the same as #12

**Comment by Possum** [comment] 2017-04-14 14:08
@McFork are you sure you have the path right? It should be "/luma/titles/TITLE_ID/locale.txt", replacing TITLE_ID with the actual title id.

**Comment by suzsuzuki** [comment] 2017-04-14 14:14
I have the same issue with the latest nightly of Luma. The file is in /luma/titles/TITLE_ID/locale.txt

**Comment by Possum** [comment] 2017-04-14 14:14
@Sonikato can you tell if it's actually saving and just not showing it? I looked into this (#12) and from what I could tell it was just a display issue. If it's actually not saving I'll need to look into it more.

If it *is* saving but the region changing is not working it may indicate a problem with Luma as @McFork suggested.

**Comment by McFork** [comment] 2017-04-14 14:29
@Possum I'm pretty sure I do. I took screencaps of the path and content of the file in case I am an idiot and didn't see something obvious: [http://imgur.com/sy2Q0od](http://imgur.com/sy2Q0od)
My version of Luma3DS is nightly v6.6-00dbbe1b from April 14th.

**Comment by Sonikato** [comment] 2017-04-14 14:51
Hi!, i forget edit this post, playing with the titleid location i put in /luma/titles/TITLE_ID/locale.txt and its works.

Thank a lot! :D

**Comment by suzsuzuki** [comment] 2017-04-14 14:53
Ok I figured out the issue. The problem is Luma Locale Swither list of default folders

My locale,txt was on \luma\locales\titles\Title_ID because it's an option for default folder. The corret as you said is /luma/titles/TITLE_ID/locale.txt

Can you just add an option for /luma/titles/TITLE_ID/locale.txt is in the list? Thanks!

**Comment by suzsuzuki** [comment] 2017-04-14 15:00
Ok nevermind. The issue continues on latest nightly. It's a Luma problem sorry! 

I tested with nightly f8984525 and worked. With latest nightly f7cc2d29 didn't works! I didn't change directory structure, just update with luma updater and after that region change stop working

**Comment by suzsuzuki** [comment] 2017-04-14 15:59
I can confirm it working know. AuroraWright fixed the issue on Luma:

https://gbatemp.net/threads/luma3ds-noob-proof-3ds-custom-firmware.411110/page-921#post-7241741

**Comment by Possum** [comment] 2017-04-14 16:02
Sweet, thanks!

I'm closing this issue, and treating #12 as a separate issue (which I think is just a display issue).

**Closed as completed by Possum** 2017-04-14 16:02 UTC
